### PR TITLE
Update example apps to use dart_eval 0.7.9, support Flutter 3.22

### PR DESCRIPTION
**Pull request by wrbl606**
In Flutter 3.22.0 deprecated Material text styles (`.headline1/2/3/...`, `body1/2/...`, etc.) got removed, breaking the bridge implementation.
Also, Flutter bindings should be regenerated for Flutter 3.22.+

### CODE REVIEW

**Comment by ethanblake4** [comment]
Thank you! Just one Q - why did you replace EvalWidget with CompilerWidget in the example?

**Comment by wrbl606** [comment]
The example wasn't working because of the lacking `program.evc` asset. I figured, to make the example easier to get up and running, it be best to replace it with `CompilerWidget` so newbies will be able to alter the demo code and see the effects without any hoops.

**Comment by wrbl606** [comment]
@ethanblake4  should I revert this back to `EvalWidget` then? Devs on Flutter stable 3.22+ might have issue running this.

**Comment by ethanblake4** [comment]
`EvalWidget` should behave the same way as `CompilerWidget` in debug mode, so I'm not sure why there would be a missing asset error unless you are trying to run it in release mode? If it does have one in debug mode there is a bug.

**Comment by wrbl606** [comment]
I don't think that running the demo app in release mode is uncommon, I'd definitely would do that if I'd to evaluate the solution.

**Comment by wrbl606** [comment]
As stated, I think the `CompilerWidget` is more beginner friendly. If users hit any performance issue with the compilation in runtime, they can the switch to the more advanced optimisation technique using the `EvalWidget`. @ethanblake4 what do you think?

**Comment by wrbl606** [comment]
@ethanblake4 You seem busy with other things, would you trust me enough to give me push access to main and an option to publish new version of the package? It has been 3 weeks since the incompatibility of flutter_eval with the newest stable Flutter version was fixed, while currently published flutter_eval version prevents the package users from upgrading to Flutter 3.22+, or, worst yet, new users are unable to try the project out while I publish new content around it.

**Comment by ethanblake4** [comment]
Hi, I'm currently on vacation in Japan so indeed will be a bit slow to get around to things. Please be patient, I should have time in the next few days. Thank you.

**Comment by wrbl606** [comment]
Have a great time!

**Pull request merged**
